[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "KitchenCopilot"
version = "1.0"

[tool.setuptools.packages.find]
include = ["utils", "utils.*"]
exclude = ["tests", "tests.*"]